/** Auto-generated from Notion ZIP export — do not edit by hand. */
import type { ChoreZipRecord } from '../types/chore';

export const CHORE_ZIP_RECORDS: ChoreZipRecord[] = [
  {
    id: "zip-000",
    exportIndex: 0,
    name: "",
    assigned: "Elijah & Roskens",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 26, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-001",
    exportIndex: 1,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "yearly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "October 17, 2024",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-002",
    exportIndex: 2,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "yearly",
    roomSlug: null,
    roomLabel: null,
    status: "In progress",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "October 18, 2024",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-003",
    exportIndex: 3,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "deep",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Cleaning Session",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "December 22, 2023",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-004",
    exportIndex: 4,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 23, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-005",
    exportIndex: 5,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 21, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-006",
    exportIndex: 6,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: "Bathroom-2ef97e9c2a3181eb8860fe936b7b084a",
    roomLabel: "🛁  Bathroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 21, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-007",
    exportIndex: 7,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-008",
    exportIndex: 8,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-009",
    exportIndex: 9,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-010",
    exportIndex: 10,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-011",
    exportIndex: 11,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-012",
    exportIndex: 12,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-013",
    exportIndex: 13,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-014",
    exportIndex: 14,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-015",
    exportIndex: 15,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-016",
    exportIndex: 16,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-017",
    exportIndex: 17,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-018",
    exportIndex: 18,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-019",
    exportIndex: 19,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-020",
    exportIndex: 20,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-021",
    exportIndex: 21,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-022",
    exportIndex: 22,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-023",
    exportIndex: 23,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-024",
    exportIndex: 24,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-025",
    exportIndex: 25,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-026",
    exportIndex: 26,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-027",
    exportIndex: 27,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-028",
    exportIndex: 28,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-029",
    exportIndex: 29,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-030",
    exportIndex: 30,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-031",
    exportIndex: 31,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-032",
    exportIndex: 32,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-033",
    exportIndex: 33,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-034",
    exportIndex: 34,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-035",
    exportIndex: 35,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-036",
    exportIndex: 36,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-037",
    exportIndex: 37,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-038",
    exportIndex: 38,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-039",
    exportIndex: 39,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020",
    roomLabel: "🛏️ Bedroom",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-040",
    exportIndex: 40,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-041",
    exportIndex: 41,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-042",
    exportIndex: 42,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-043",
    exportIndex: 43,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-044",
    exportIndex: 44,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-045",
    exportIndex: 45,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-046",
    exportIndex: 46,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-047",
    exportIndex: 47,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-048",
    exportIndex: 48,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-049",
    exportIndex: 49,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-050",
    exportIndex: 50,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-051",
    exportIndex: 51,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-052",
    exportIndex: 52,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-053",
    exportIndex: 53,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-054",
    exportIndex: 54,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-055",
    exportIndex: 55,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-056",
    exportIndex: 56,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-057",
    exportIndex: 57,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-058",
    exportIndex: 58,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-059",
    exportIndex: 59,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-060",
    exportIndex: 60,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-061",
    exportIndex: 61,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-062",
    exportIndex: 62,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-063",
    exportIndex: 63,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-064",
    exportIndex: 64,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-065",
    exportIndex: 65,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-066",
    exportIndex: 66,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-067",
    exportIndex: 67,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-068",
    exportIndex: 68,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-069",
    exportIndex: 69,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-070",
    exportIndex: 70,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-071",
    exportIndex: 71,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-072",
    exportIndex: 72,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-073",
    exportIndex: 73,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-074",
    exportIndex: 74,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-075",
    exportIndex: 75,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-076",
    exportIndex: 76,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-077",
    exportIndex: 77,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-078",
    exportIndex: 78,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Pantry-2ef97e9c2a3181979138c282576cd910",
    roomLabel: "🥫 Pantry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-079",
    exportIndex: 79,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-080",
    exportIndex: 80,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-081",
    exportIndex: 81,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-082",
    exportIndex: 82,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-083",
    exportIndex: 83,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-084",
    exportIndex: 84,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-085",
    exportIndex: 85,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-086",
    exportIndex: 86,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-087",
    exportIndex: 87,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-088",
    exportIndex: 88,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-089",
    exportIndex: 89,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-090",
    exportIndex: 90,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-091",
    exportIndex: 91,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200",
    roomLabel: "🍽️ Dining Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-092",
    exportIndex: 92,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-093",
    exportIndex: 93,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-094",
    exportIndex: 94,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-095",
    exportIndex: 95,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-096",
    exportIndex: 96,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-097",
    exportIndex: 97,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-098",
    exportIndex: 98,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-099",
    exportIndex: 99,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-100",
    exportIndex: 100,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-101",
    exportIndex: 101,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-102",
    exportIndex: 102,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-103",
    exportIndex: 103,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-104",
    exportIndex: 104,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-105",
    exportIndex: 105,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-106",
    exportIndex: 106,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-107",
    exportIndex: 107,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-108",
    exportIndex: 108,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Entry-2ef97e9c2a3181f78171fb35aa12d167",
    roomLabel: "🚪 Entry",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-109",
    exportIndex: 109,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-110",
    exportIndex: 110,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-111",
    exportIndex: 111,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-112",
    exportIndex: 112,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-113",
    exportIndex: 113,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-114",
    exportIndex: 114,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-115",
    exportIndex: 115,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-116",
    exportIndex: 116,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-117",
    exportIndex: 117,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Halls-2ef97e9c2a31812b92fed8399ea05356",
    roomLabel: "🚶 Halls",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-118",
    exportIndex: 118,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c",
    roomLabel: "🗑️ Trash & Recycling",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-119",
    exportIndex: 119,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-120",
    exportIndex: 120,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-121",
    exportIndex: 121,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-122",
    exportIndex: 122,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-123",
    exportIndex: 123,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-124",
    exportIndex: 124,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-125",
    exportIndex: 125,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-126",
    exportIndex: 126,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-127",
    exportIndex: 127,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-128",
    exportIndex: 128,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-129",
    exportIndex: 129,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-130",
    exportIndex: 130,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-131",
    exportIndex: 131,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-132",
    exportIndex: 132,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-133",
    exportIndex: 133,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-134",
    exportIndex: 134,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-135",
    exportIndex: 135,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8",
    roomLabel: "🚽 Half Bath",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-136",
    exportIndex: 136,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-137",
    exportIndex: 137,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-138",
    exportIndex: 138,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Daily",
    cadence: "daily",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-139",
    exportIndex: 139,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-140",
    exportIndex: 140,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-141",
    exportIndex: 141,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-142",
    exportIndex: 142,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-143",
    exportIndex: 143,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-144",
    exportIndex: 144,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-145",
    exportIndex: 145,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Monthly",
    cadence: "monthly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-146",
    exportIndex: 146,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "Weekly",
    cadence: "weekly",
    roomSlug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9",
    roomLabel: "👨‍👩‍👧‍👦 Family Room",
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "",
    inbox: true,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-147",
    exportIndex: 147,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-148",
    exportIndex: 148,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 21, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-149",
    exportIndex: 149,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "deep",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Cleaning Session",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 19, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-150",
    exportIndex: 150,
    name: "",
    assigned: "",
    assignedTo: "",
    frequency: "",
    cadence: "recurring",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: true,
    scheduledDate: "January 27, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-151",
    exportIndex: 151,
    name: "",
    assigned: "",
    assignedTo: "Jeremiah",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-152",
    exportIndex: 152,
    name: "",
    assigned: "",
    assignedTo: "Herschel",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-153",
    exportIndex: 153,
    name: "",
    assigned: "",
    assignedTo: "Nox",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-154",
    exportIndex: 154,
    name: "",
    assigned: "",
    assignedTo: "Jeremiah",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-155",
    exportIndex: 155,
    name: "",
    assigned: "",
    assignedTo: "Jeremiah",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-156",
    exportIndex: 156,
    name: "",
    assigned: "",
    assignedTo: "Nox",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-157",
    exportIndex: 157,
    name: "",
    assigned: "",
    assignedTo: "Nox",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
  {
    id: "zip-158",
    exportIndex: 158,
    name: "",
    assigned: "",
    assignedTo: "Lorraine",
    frequency: "",
    cadence: "seasonal",
    roomSlug: null,
    roomLabel: null,
    status: "Not started",
    type: "Chores",
    notes: "",
    line: "_______________",
    inbox: false,
    scheduledDate: "February 3, 2026",
    currentDate: "May 16, 2026",
    completionPct: "0%",
    tasksCompleted: "",
    totalTasks: "",
  },
];

export const CHORE_ZIP_RECORD_COUNT = 159;
export const CHORE_ZIP_ROOMS = [
  { slug: "Dining-Room-2ef97e9c2a318192bdd0f0418b269200", label: "🍽️ Dining Room" },
  { slug: "Family-Room-2ef97e9c2a3181c7b087f2438a1f9bf9", label: "👨‍👩‍👧‍👦 Family Room" },
  { slug: "Trash-Recycling-2ef97e9c2a3181249089f3915f94b75c", label: "🗑️ Trash & Recycling" },
  { slug: "Entry-2ef97e9c2a3181f78171fb35aa12d167", label: "🚪 Entry" },
  { slug: "Halls-2ef97e9c2a31812b92fed8399ea05356", label: "🚶 Halls" },
  { slug: "Half-Bath-2ef97e9c2a3181d881c4f8476b0304b8", label: "🚽 Half Bath" },
  { slug: "Bathroom-2ef97e9c2a3181eb8860fe936b7b084a", label: "🛁  Bathroom" },
  { slug: "Bedroom-2ef97e9c2a318104bfe5c06efed42020", label: "🛏️ Bedroom" },
  { slug: "Pantry-2ef97e9c2a3181979138c282576cd910", label: "🥫 Pantry" },
] as const;
