import type { CanvasComponent } from "./uiBuilderLayout";
import { uiComponents } from "./uiBuilderLayout";
import { COMPONENT_VARIANT_OPTIONS } from "./componentVariantOptions";
import standaloneRenderBody from "./_standaloneRenderFragment.txt?raw";

function itemLiteral(item: CanvasComponent): string {
  const lines: string[] = [
    "  {",
    `    instanceId: ${JSON.stringify(item.instanceId)},`,
    `    definitionId: ${JSON.stringify(item.definitionId)},`,
    `    title: ${JSON.stringify(item.title)},`,
    `    body: ${JSON.stringify(item.body)},`,
    `    accent: ${JSON.stringify(item.accent)},`,
    `    size: ${JSON.stringify(item.size)},`,
  ];
  if (item.settings && Object.keys(item.settings).length > 0) {
    lines.push(`    settings: ${JSON.stringify(item.settings)},`);
  }
  lines.push("  }");
  return lines.join("\n");
}

function buildComponentLabelsMap(): string {
  const entries = uiComponents.map(
    (c) => `  ${JSON.stringify(c.id)}: ${JSON.stringify(c.name)}`,
  );
  return [
    "const COMPONENT_LABELS: Record<string, string> = {",
    entries.join(",\n"),
    "};",
    "",
    "function labelFor(definitionId: string): string {",
    "  return COMPONENT_LABELS[definitionId] ?? definitionId;",
    "}",
  ].join("\n");
}

const STANDALONE_RENDER_EXPORTED_PREVIEW = standaloneRenderBody.replace(
  "__VARIANT_JSON__",
  JSON.stringify(COMPONENT_VARIANT_OPTIONS),
);

/**
 * Standalone TSX for `ExportedUiLayout` (React types only; no app imports).
 */
export function generateExportedUiLayoutTsx(canvas: CanvasComponent[]): string {
  const arrayBody = canvas.map((row) => itemLiteral(row)).join(",\n");
  const renderFn = STANDALONE_RENDER_EXPORTED_PREVIEW;
  return [
    "/**",
    " * This file is standalone except for CSS. Import ui-builder.css or copy the needed wd-* styles into your app.",
    " * Generated by 491WD UI Builder.",
    " */",
    "",
    'import type { CSSProperties, ReactElement } from "react";',
    'import { createElement } from "react";',
    "",
    "export type ExportedCanvasItem = {",
    "  instanceId: string;",
    "  definitionId: string;",
    "  title: string;",
    "  body: string;",
    "  accent: string;",
    "  size: \"compact\" | \"normal\" | \"wide\";",
    "  settings?: Record<string, string | number | boolean | string[]>;",
    "};",
    "",
    buildComponentLabelsMap(),
    "",
    "const EXPORTED_ITEMS: ExportedCanvasItem[] = [",
    arrayBody,
    "];",
    "",
    renderFn,
    "",
    "export default function ExportedUiLayout() {",
    "  return (",
    '    <main className="wd-ui-preview-page">',
    '      <header className="wd-ui-preview-hero">',
    '        <p className="wd-ui-preview-eyebrow">491WD export</p>',
    "        <h1>Exported UI layout</h1>",
    '        <p className="wd-ui-preview-lede">',
    "          Static read-only layout {EXPORTED_ITEMS.length} component",
    '          {EXPORTED_ITEMS.length === 1 ? "" : "s"}.',
    "        </p>",
    "      </header>",
    '      <div className="wd-ui-preview-grid">',
    "        {EXPORTED_ITEMS.map((row) => (",
    "          <article",
    "            key={row.instanceId}",
    '            className={"wd-ui-preview-card wd-size-" + row.size}',
    '            style={{ \"--wd-accent\": row.accent } as CSSProperties}',
    "          >",
    '            <div className="wd-card-toolbar wd-ui-preview-card-meta">',
    '              <span className="wd-ui-preview-pill">{labelFor(row.definitionId)}</span>',
    "            </div>",
    '            <div className="wd-ui-preview-card-body wd-ui-preview-readonly">',
    "              {renderExportedPreview(row.definitionId, row)}",
    "            </div>",
    "          </article>",
    "        ))}",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

